### ISSUE TITLE
日本地図がギャッてなる

### ISSUE THREAD

**Issue by miholovesq** [enpitut2019/yusaku-app#15]
![18E05B33-5BD7-4B1D-90C2-8BC81E591580](https://user-images.githubusercontent.com/1164104/62505300-182fab00-b837-11e9-9d9a-e4e8e8ba3829.jpeg)
なんぞ？
iPhoneのChromeです。

**Comment by yaplus** [comment]
a04dc449e638d99d49945d53c4582b327fa9de06 で修正しました。
