### ISSUE TITLE
ランダム性が重要なら、Math.randomはセキュリティ的によろしくないので、セキュアなランダムをつかいましょう。そうでもない気がするので別に無視してもいいかも。

### ISSUE THREAD

**Issue by kyonmm** [enpitut2019/yusaku-app#16]
https://github.com/enpitut2019/yusaku-app/blob/c32166ef87cd3f91ac7741f2218b2b75435f1708/src/JapanMap.js#L72

こんかいは対象外かもしれない。けど、いちおうあげておきます。
対処するならつぎみたいなかんじのコードになります。

```
const crypto = window.crypto || window.msCrypto;
var array = new Uint32Array(1);
crypto.getRandomValues(array); // Compliant for security-sensitive use cases
```

**Comment by yaplus** [comment]
ありがとうございます。勉強になりました。テスト用のランダムなコードなので、現時点 ( 76f1a3763fe395ffc31bf2576bb340545a6f13ed ) で使用していませんし、将来的に削除する予定です。
